package-lock.json, package.json, src/components/admin/AdminMain.tsx, src/components/admin/MainHeader.tsx, src/components/admin/SideBar.tsx, src/types/IAdmin.ts
사이드바 UI 
사이드바 UI 및 토글버튼 만들었습니다. 또한 페이지마다 출력이 다르게 필요한부분다르게 하였습니다.
사이드바, 메인부분헤더 컴포넌트 분리하였습니다.
react-icons 라이브러리 설치하였습니다. 
디자인적으로 태클좀 부탁드립니다.
=> FEAT:사이드바UI작업

package-lock.json, package.json, src/components/main/MainCalendar.tsx, src/pages/index.tsx, src/pages/main.tsx, tailwind.config.js
메인페이지에 사용되는 달력 구현
1. 월별 일자 보이게 하였음
2. next, prev버튼 누르면 월이 변경되고 그에 맞춰 일자도 변경
3. 당일색은 다른 색으로 표현
4. 해당월 외의 일자는 font-color 회색으로 변경
5. 일자 호버시 다른 색상
#7 
1. moment 라이브러리, date-fns 라이브러리 사용했습니다.
- npm i moment
- npm i date-fns --save
하시면 됩니다!
2. 아직 공휴일은 적용이 안되었습니다... 추후에 적용하도록 하겠습니다 😄
3. commit은 불의의 사고로 인해 자료를 옮기느라 한 번 밖에 안되었습니다... 😢  
4. 수정사항이나 추가사항 있으시면 말씀해주세요~
=> feat:달력기본기능구현

package-lock.json, src/components/admin/AdminEmployeeList.tsx, src/components/admin/AdminMain.tsx, src/components/admin/AdminMainHeader.tsx, src/components/admin/AdminSideBar.tsx, src/constants/Option.tsx, src/pages/_app.tsx, src/pages/admin-modify.tsx
관리자페이지  수정페이지UI
관리자 페이지의 수정페이지 부분 UI작업하였습니다
기존 아이콘 히어로아이콘으로 변경하였습니다.
이거 머지 안해도 될거같네요 두번쨰 올린거에 이미 이내용도 있어서요 이거 설명용으로 남겨두겠습니다.
=> FEAT:modify UI create

src/components/admin/AdminSignInBox.tsx, src/components/admin/AdminSignInInput.tsx, src/pages/admin-signin.tsx
API 연동 전 기초 UI 작업했습니다
closed #32
=> FEAT: 관리자 로그인 UI

src/components/member/MemberBoard.tsx, src/components/member/MemberDetail.tsx, src/components/member/MemberHeader.tsx, src/components/member/MemberInfo.tsx, src/components/member/MemberSideBar.tsx, src/pages/member.tsx
=> STYLE: 마이페이지 스타일 수정

src/components/member/MemberEdit.tsx, src/components/member/MyPageList.tsx, src/pages/_app.tsx, src/pages/api/RestList.ts, src/pages/api/WorkList.ts, src/pages/member-edit.tsx, src/pages/member-list.tsx, src/types/IMyPages.ts
연차 당직 페이지 ui 및 기능구현
연차 당직 페이지 작업
=> feat: 연차 당직 페이지작업

src/components/admin/AdminMain.tsx, src/components/admin/AdminMainHeader.tsx, src/components/admin/AdminRequestList.tsx, src/components/admin/AdminSideBar.tsx
관리자페이지 전체 UI수정
관리자페이지 전체 UI수정하였습니다.
이전에 작업한거 다날라갔습니다,,,
=> FEAT:관리자페이지 전체UI수정

src/components/common/ManagerModal.tsx, src/components/member/MemberBoard.tsx, src/components/member/MemberDetail.tsx, src/components/member/MemberEdit.tsx, src/components/member/MemberInfo.tsx, src/components/member/MemberSideBar.tsx, src/pages/member-edit.tsx, src/pages/member.tsx
=> Feat/member/edit 마이페이지 2차 수정

src/components/auth/AuthChangePwInput.tsx, src/components/auth/AuthFindPwInput.tsx, src/components/common/Input.tsx
1. 비밀번호 변경(change-pw) 유효성 검사
2. input 스타일링 변경
=> FEAT: 비밀번호 변경 폼 유효성 검사

package-lock.json, package.json, src/components/auth/sign-up/AuthSignUpInput.tsx, src/components/common/AuthDropdown.tsx, src/components/common/Dropdown.tsx, src/components/common/Input.tsx, src/components/common/SinglePicker.tsx, src/constants/constants.ts, src/constants/option.ts, src/pages/sign-up.tsx, src/recoil/signUp.ts, src/types/ICommon.ts, src/types/ISignUp.ts
1. Auth Dropdown 생성, 회원가입 폼에 적용했습니다.
1. npm i 부탁드립니다.
2. 추후 공용으로 쓸 수 있도록 수정 필요
=> FEAT: Auth Dropdown 생성

src/components/member/MemberBoard.tsx, src/components/member/MemberDetail.tsx, src/components/member/MemberEdit.tsx, src/components/member/MemberInfo.tsx, src/components/member/MemberInfoEdit.tsx, src/components/member/MyPageList.tsx, src/pages/member-edit.tsx, src/pages/member-list.tsx, src/pages/member.tsx
=> feat:마이페이지 전체 UI 3차 수정

src/api/auth/signUp.ts, src/api/auth/signin.ts, src/components/auth/sign-in/AuthSignInBox.tsx, src/components/auth/sign-in/AuthSignInInput.tsx, src/components/auth/sign-up/AuthSignUpBox.tsx, src/components/auth/sign-up/AuthSignUpInput.tsx, src/components/auth/sign-up/AuthValidCheck.tsx, src/components/common/AuthDropdown.tsx, src/components/common/Pagination.tsx, src/components/common/SinglePicker.tsx, src/constants/option.ts, src/pages/sign-up.tsx, src/recoil/signUp.ts, src/recoil/signin.ts, src/types/ISignUp.ts, src/types/ISignin.ts
회원가입, 로그인 API 연동
closed #69 
closed #70 
로그인 성공 시 동작은 아직 구현 전입니다. 네트워크 탭을 통해서 확인하시면 됩니다
=> FEAT: 회원가입, 로그인 API 연동

src/components/admin/AdminMain.tsx, src/components/admin/AdminManageList.tsx, src/components/admin/AdminModify.tsx, src/components/admin/AdminRequestList.tsx, src/components/common/Loading.tsx, src/constants/option.ts, src/types/IAdmin.ts
=> FEAT:로딩컴포넌트추가

src/api/auth/changePw.ts, src/components/auth/AuthChangePwInput.tsx, src/types/IAuth.ts
비밀번호 변경 API 연결
비밀번호 변경 API 연결
closed #72
=> FEAT: 비밀번호 변경 API 연결

src/api/auth/changePw.ts, src/api/auth/findPw.ts, src/api/auth/signUp.ts, src/api/axios.ts, src/components/admin/AdminMain.tsx, src/components/admin/AdminManageList.tsx, src/components/admin/AdminModify.tsx, src/components/admin/AdminRequestList.tsx, src/components/auth/AuthChangePwInput.tsx, src/components/auth/AuthFindPwInput.tsx, src/components/auth/sign-in/AuthSignInBox.tsx, src/components/auth/sign-up/AuthSignUpBox.tsx, src/components/auth/sign-up/AuthSignUpInput.tsx, src/components/common/Loading.tsx, src/constants/constants.ts, src/constants/option.ts, src/recoil/signUp.ts, src/types/IAdmin.ts, src/types/IAuth.ts, src/types/ISignUp.ts, src/types/ISignin.ts
FEAT: 회원가입 폼 예외 처리 및 회원가입 시, 로그인 페이지로 이동
=> FEAT: 회원가입 페이지 예외처리 및 성공 시 로그인 이동

src/api/admin/modify.ts, src/components/admin/AdminModify.tsx, src/types/IAdmin.ts
modifyRes form-data수정 
admin put api 리팩토링
=> FIX: admin put api 리팩토링

src/api/admin/modify.ts, src/components/admin/AdminModify.tsx
=> FEAT: put api 수정

src/api/auth/findPw.ts, src/api/auth/resetPw.ts, src/components/auth/AuthFindPwInput.tsx, src/components/auth/AuthResetBox.tsx, src/components/auth/AuthResetPwInput.tsx, src/components/auth/sign-in/AuthSignInBox.tsx, src/pages/reset-pw.tsx, src/types/IAuth.ts
=> FEAT: 비밀번호 변경 페이지 분할

src/components/auth/sign-in/AuthSignInBox.tsx
=> FEAT: cookie 저장 방식 추가

package-lock.json, package.json, src/api/main/dayoff.ts, src/components/common/ApproveModal.tsx, src/components/main/MainHeader.tsx
=> FEAT:캘린더 API 연동작업 1

src/api/auth/changePw.ts, src/api/auth/findPw.ts, src/api/auth/resetPw.ts, src/api/auth/signUp.ts, src/api/auth/signin.ts, src/components/auth/auth.tsx, src/components/auth/find-pw/AuthFindPwInput.tsx, src/components/auth/reset-pw/AuthResetPwBox.tsx, src/components/auth/reset-pw/AuthResetPwInput.tsx, src/components/auth/sign-up/AuthSignUpBox.tsx, src/components/member/MyPageList.tsx, src/pages/change-pw.tsx, src/pages/find-pw.tsx, src/pages/reset-pw.tsx, src/types/IAuth.ts
=> FEAT: 비밀번호 reset 기능 추가

src/api/auth/resetPw.ts, src/api/auth/signin.ts, src/components/auth/change-pw/AuthChangePwInput.tsx, src/components/auth/reset-pw/AuthResetPwBox.tsx, src/components/auth/reset-pw/AuthResetPwInput.tsx, src/components/auth/sign-in/AuthSignInBox.tsx, src/types/IAuth.ts
=> FEAT: 비 로그인 시 비밀번호 재설정

src/api/auth/changePw.ts, src/components/auth/change-pw/AuthChangePwInput.tsx, src/types/IAuth.ts
(로그인 시) 비밀번호 변경 ChangePw
1. request에 필요한 employeeId값을 얻기 위해 cookie.get('employeeId')
2. 기타 누락된 타입 선언
=> FEAT: cookie에서 employeeId get

src/pages/_document.tsx
FIX: Content-Security-Policy 오류 해결
=> FIX: Content-Security-Policy 오류 해결

src/pages/_document.tsx
Content-Security-Policy 수정 및 삭제
=> FIX: Content-Security-Policy 수정

src/api/auth/changePw.ts, src/components/auth/sign-up/AuthSignUpInput.tsx
1. 400 에러 시, alert 에러 메시지
2. 비밀번호 확인 과정 유효성 검사
3.
=> FEAT: 회원가입 예외처리 및 유효성 검사 기능 추가

src/components/auth/change-pw/AuthChangePwInput.tsx, src/components/auth/sign-in/AuthSignInBox.tsx
로그인 성공 시 Role에 따른 리다이렉션 구현
```
// 관리자면 admin-manage 페이지로 라우팅
if (response.data.data.employee.role === 'ADMIN') {
router.push('/admin-manage');
} else {
// main 페이지로 라우팅
router.push('/main');
}
```
=> FEAT: Role에 따른 리다이렉션 

src/api/admin/dayOff.ts, src/api/admin/dayOffStatus.ts, src/api/admin/duty.ts, src/api/admin/dutyStatus.ts, src/api/admin/manage.ts, src/api/admin/modalDayOff.ts, src/api/admin/modalDuty.ts, src/api/admin/modify.ts, src/api/admin/modifyDetail.ts, src/api/auth/changePw.ts, src/api/main/dayoff.ts, src/api/main/duty.ts, src/api/main/schedules.ts, src/api/member/memberInfo.ts, src/api/member/memberList.ts, src/api/member/memberModify.ts, src/api/member/personalInfo.ts, src/components/admin/AdminMainHeader.tsx, src/components/auth/change-pw/AuthChangePwInput.tsx, src/components/auth/find-pw/AuthFindPwInput.tsx, src/components/auth/sign-in/AuthSignInBox.tsx, src/components/auth/sign-in/AuthSignInInput.tsx, src/components/auth/sign-up/AuthSignUpInput.tsx, src/components/common/ApproveModal.tsx, src/components/main/Main.tsx, src/pages/404.tsx, src/pages/sign-in.tsx, src/types/IMain.ts
-  pages 폴더 내 404.tsx을 통해 모든 404 에러 페이지를 관할
- 비 로그인 상태 비밀번호 찾기 페이지 유효성 검사
closed #132
=> FEAT: 404에러 페이지 / 비 로그인 비밀번호 찾기 작업

src/components/auth/AuthLayout.tsx, src/components/auth/reset-pw/AuthResetPwInput.tsx, src/components/auth/sign-in/AuthSignInBox.tsx, src/components/auth/sign-in/AuthSignInInput.tsx, src/components/auth/sign-up/AuthSignUpInput.tsx, src/components/auth/sign-up/AuthSignUpTitle.tsx, src/components/auth/sign-up/AuthValidCheck.tsx, src/components/common/AuthDropdown.tsx, src/components/common/Input.tsx, src/constants/constants.ts, src/types/IAuth.ts
=> FEAT: 정규표현식 변수화 및 세부 스타일링

src/components/admin/AdminMain.tsx, src/components/admin/AdminMainHeader.tsx, src/components/admin/AdminManageList.tsx, src/components/admin/AdminModal.tsx, src/components/admin/AdminModify.tsx, src/components/admin/AdminSideBar.tsx
=> FEAT:관리자페이지UI수정

README.md
=> FEAT:리드미작성

src/api/main/duty.ts, src/components/common/ApproveModal.tsx, src/components/common/ManagerModal.tsx, src/components/main/Main.tsx, src/components/main/MainCalendar.tsx, src/components/main/MainMenuBar.tsx, src/recoil/main.ts, src/types/IDayOff.ts, src/types/IDuty.ts
=> feat:api7차

src/api/admin/duty.ts, src/api/admin/manage.ts, src/api/auth/validPw.ts, src/api/member/memberInfo.ts, src/api/member/memberList.ts, src/components/admin/AdminManageList.tsx, src/components/auth/change-pw/AuthChangePwInput.tsx
토큰 인증 없이 페이지 접근 시 발생하는 403에러 핸들링
1. 403에러 발생 예상 지점 API에 에러 핸들링
2. 에러 발생 지점 접근 시 홈으로 location.replace
``` alert(error.response.data.message);
location.replace('/');
return error;
}```
=> FIX: 403 ERROR 수정

src/api/main/schedules.ts, src/components/main/Main.tsx
Main.tsx 403 ERROR 수정
메인페이지 비허가 다이렉션 에러 수정
=> FIX: Main.tsx 403 ERROR 수정

src/components/member/MemberBoard.tsx, src/components/member/MemberDetail.tsx, src/components/member/MemberHeader.tsx, src/components/member/MemberInfoEdit.tsx, src/components/member/MemberLayout.tsx, src/components/member/MyPageList.tsx, src/constants/options.ts, src/pages/member-edit.tsx, src/pages/member-list.tsx, src/pages/member.tsx
=> FEAT:마이페이지 UI

src/api/auth/resetPw.ts
=> FIX: Authorizaion Token 전송 제외

src/components/member/MemberHeader.tsx, src/components/member/MemberInfoEdit.tsx
=> FEAT:마이페이지링크추가

src/api/auth/logIn.ts, src/api/auth/validPw.ts, src/components/auth/change-pw/AuthChangePwInput.tsx, src/components/auth/reset-pw/AuthResetPwInput.tsx, src/pages/404.tsx
=> FIX: 다이렉션 오류 해결

src/components/auth/find-pw/AuthFindPwBox.tsx, src/components/auth/find-pw/AuthFindPwInput.tsx, src/components/auth/find-pw/AuthSentEmailBox.tsx, src/components/auth/sign-in/AuthSignInBox.tsx, src/components/auth/sign-up/AuthSignUpBox.tsx, src/components/common/Loading.tsx, src/pages/sent-email.tsx
1. 로딩 컴포넌트 적용중 (추후 더 적용 필요)
2. 비밀번호 찾기 위해 이메일 전송 시, 전송 완료 페이지로 이동
=> FEAT:  로딩 적용 및 메일 전송 완료 페이지 생성

src/api/admin/dayOffStatus.ts, src/api/admin/duty.ts, src/api/admin/manage.ts, src/api/member/memberInfo.ts, src/api/member/memberList.ts, src/api/member/memberModify.ts, src/api/member/personalInfo.ts, src/components/admin/AdminMain.tsx, src/components/admin/AdminSignInBox.tsx, src/components/auth/AuthLayout.tsx, src/components/auth/change-pw/AuthChangePwBox.tsx, src/components/auth/find-pw/AuthFindPwBox.tsx, src/components/auth/find-pw/AuthSentEmailBox.tsx, src/components/auth/reset-pw/AuthResetPwBox.tsx, src/components/auth/sign-in/AuthSignInBox.tsx, src/components/auth/sign-up/AuthSignUpBox.tsx, src/components/auth/sign-up/AuthSignUpInput.tsx, src/components/common/AuthBox.tsx, src/components/common/AuthDropdown.tsx, src/components/common/Button.tsx, src/components/common/Dialog.tsx, src/components/common/SearchSiteButton.tsx, src/components/member/MemberLayout.tsx, src/pages/sent-email.tsx, src/pages/sign-in.tsx, src/pages/sign-up.tsx, src/types/ICommon.ts, tailwind.config.js
1. cookie에 저장된 role에 따라 접근 허가
2. 비밀번호 재설정 메일 전송 후 페이지 이동
=> FEAT: 비허가 접근 및 재설정 메일 전송 후 접근 페이지

src/components/admin/AdminMainHeader.tsx, src/components/main/MainHeader.tsx
=> feat:로그아웃시role토큰삭제

package-lock.json, package.json, src/api/admin/dayOff.ts, src/components/admin/AdminRequestList.tsx, src/components/auth/find-pw/AuthFindPwInput.tsx, src/components/common/Dialog.tsx, src/components/main/MainCalendar.tsx, src/components/member/MemberBoard.tsx, src/components/member/MemberDetail.tsx, src/components/member/MemberHeader.tsx, src/components/member/MemberInfoEdit.tsx, src/components/member/MemberLayout.tsx, src/components/member/MemberSideBar.tsx, src/components/member/MyPageList.tsx, src/pages/admin-leave.tsx, src/pages/member-edit.tsx, src/pages/member-list.tsx, src/pages/member.tsx, src/recoil/memberInfo.ts, src/types/IPersonal.ts
=> REFACTOR: 마이페이지 리팩토링
